name: 'Woo Extension - Prepare New Release'
run-name:  Woo Extension - Prepare New Release `${{ github.event.inputs.type }}/${{ github.event.inputs.version }}` from `${{ github.ref_name || github.ref }}` by @${{ github.actor }}

# **What it does**: Does release preparation, creates bracnh, TODO lsit in PR, generate changelog.
# **Why we have it**: To support dev automating as much as possible, and leave nice reference for the consumers
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
    inputs:
      ## In the future we could infer that version from the changelog, or bump it via major|minor|patch.
      version:
        description: 'Version number to be released'
        required: true
      type:
        description: 'Type of the release (release|hotfix)'
        required: true
        default: 'release'
      wp_version:
        description: 'WordPress tested up to'
      wc_version:
        description: 'WooCommerce tested up to'


jobs:
  Prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: woocommerce/grow/prepare-extension-release@actions-v1.5.2-pre
        with:
          version: ${{ github.event.inputs.version }}
          type: ${{ github.event.inputs.type }}
          wp_version: ${{ github.event.inputs.wp_version }}
          wc_version: ${{ github.event.inputs.wc_version }}
          main_branch: 'trunk'
