name: '[HACK DAY] Woo Extension - Prepare New Release'
run-name:  Woo Extension - Prepare New Release `${{ github.event.inputs.type }}/${{ github.event.inputs.version }}` from `${{ github.ref_name || github.ref }}` by @${{ github.actor }}

# **What it does**: Does release preparation, creates bracnh, TODO lsit in PR, generate changelog.
# **Why we have it**: To support dev automating as much as possible, and leave nice reference for the consumers
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
    inputs:
      ## In the future we could infer that version from the changelog, or bump it via major|minor|patch.
      version:
        description: 'Version number to be released'
        required: true
      type:
        description: 'Type of the release (release|hotfix)'
        required: true
        default: 'release'
      wp_version:
        description: 'WP tested up to version'
      wc_version:
        description: 'WC tested up to version'

jobs:
  PrepareRelease:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Set release branch name
        id: release-vars
        run: echo "branch=${{ github.event.inputs.type }}/${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare node
        uses: ./packages/js/github-actions/actions/prepare-node
        with:
          node-version: 14
          cache-dependency-path: ./packages/js/github-actions/package-lock.json
          install-deps: "no"

      # The checkout revision of this repo itself doesn't have the built actions,
      # so it needs to build them before using it locally.
      - name: Build actions
        run: |
          cd ./packages/js/github-actions
          npm ci --ignore-scripts
          npm run build
          cd -

      - name: Prepare release commits
        # Use the github-actions bot account to commit.
        # https://api.github.com/users/github-actions%5Bbot%5D
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -b ${{ steps.release-vars.outputs.branch }}

          git commit --allow-empty -q -m "Start \\\`${{ steps.release-vars.outputs.branch }}\\\`."
          git push --set-upstream origin ${{ steps.release-vars.outputs.branch }}

      - name: Create a pull request for release
        uses: actions/github-script@v6
        with:
          script: |
            const workspace = '${{ github.workspace }}';
            const { default: script } = await import( `${ workspace }/.github/scripts/woo-extension-create-pr-for-release.mjs` );
            await script( {
              github,
              context,
              base: '${{ github.ref }}',
              refName: '${{ steps.release-vars.outputs.branch }}',
              type: '${{ github.event.inputs.type }}',
              version: '${{ github.event.inputs.version }}',
              wp_version,
              wc_version
            } );

      # - name: Run WooRelease simulate
      #   # Use the github-actions bot account to commit.
      #   # https://api.github.com/users/github-actions%5Bbot%5D
      #   run: |
      #     wget -O /tmp/z.$$ https://github.com/woocommerce/woorelease/releases/download/2.4.0/woorelease.zip && unzip /tmp/z.$$ rm /tmp/z.$$

      #     php

      #     TODAY=$(date '+%Y-%m-%d')
      #     NEXT_VER="${{ github.event.inputs.version }}"
      #     REALESE_BRANCH="${{ github.event.inputs.type }}/${{ github.event.inputs.version }}"

      #     git config user.name github-actions[bot]
      #     git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      #     git checkout -b ${{ steps.release-vars.outputs.branch }}

      #     git commit --allow-empty -q -m "Start \\\`${{ steps.release-vars.outputs.branch }}\\\`."
      #     git push --set-upstream origin ${{ steps.release-vars.outputs.branch }}
